package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsManuorderparam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsManuorderparam extends BaseGpsManuorderparam<GpsManuorderparam> {
	public static final GpsManuorderparam dao = new GpsManuorderparam().dao();
}
