package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsTcData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsTcData extends BaseGpsTcData<GpsTcData> {
	public static final GpsTcData dao = new GpsTcData().dao();
}
