package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsUsertype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsUsertype extends BaseGpsUsertype<GpsUsertype> {
	public static final GpsUsertype dao = new GpsUsertype().dao();
}
