package com.jimi.mes_server.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("Gps_ManuOrderParam", "Id", GpsManuorderparam.class);
		arp.addMapping("Gps_TestPlan", "TestPlanId", GpsTestplan.class);
		arp.addMapping("Gps_User", "UserId", GpsUser.class);
		arp.addMapping("Gps_UserType", "TypeId", GpsUsertype.class);
	}
}

