package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsManuorderparam<M extends BaseGpsManuorderparam<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setSoftModel(java.lang.String SoftModel) {
		set("SoftModel", SoftModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("SoftModel");
	}

	public M setSN1(java.lang.String SN1) {
		set("SN1", SN1);
		return (M)this;
	}
	
	public java.lang.String getSN1() {
		return getStr("SN1");
	}

	public M setSN2(java.lang.String SN2) {
		set("SN2", SN2);
		return (M)this;
	}
	
	public java.lang.String getSN2() {
		return getStr("SN2");
	}

	public M setSN3(java.lang.String SN3) {
		set("SN3", SN3);
		return (M)this;
	}
	
	public java.lang.String getSN3() {
		return getStr("SN3");
	}

	public M setBoxNo1(java.lang.String BoxNo1) {
		set("BoxNo1", BoxNo1);
		return (M)this;
	}
	
	public java.lang.String getBoxNo1() {
		return getStr("BoxNo1");
	}

	public M setBoxNo2(java.lang.String BoxNo2) {
		set("BoxNo2", BoxNo2);
		return (M)this;
	}
	
	public java.lang.String getBoxNo2() {
		return getStr("BoxNo2");
	}

	public M setProductDate(java.lang.String ProductDate) {
		set("ProductDate", ProductDate);
		return (M)this;
	}
	
	public java.lang.String getProductDate() {
		return getStr("ProductDate");
	}

	public M setColor(java.lang.String Color) {
		set("Color", Color);
		return (M)this;
	}
	
	public java.lang.String getColor() {
		return getStr("Color");
	}

	public M setWeight(java.lang.String Weight) {
		set("Weight", Weight);
		return (M)this;
	}
	
	public java.lang.String getWeight() {
		return getStr("Weight");
	}

	public M setQty(java.lang.String Qty) {
		set("Qty", Qty);
		return (M)this;
	}
	
	public java.lang.String getQty() {
		return getStr("Qty");
	}

	public M setProductNo(java.lang.String ProductNo) {
		set("ProductNo", ProductNo);
		return (M)this;
	}
	
	public java.lang.String getProductNo() {
		return getStr("ProductNo");
	}

	public M setVersion(java.lang.String Version) {
		set("Version", Version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("Version");
	}

	public M setIMEIStart(java.lang.String IMEIStart) {
		set("IMEIStart", IMEIStart);
		return (M)this;
	}
	
	public java.lang.String getIMEIStart() {
		return getStr("IMEIStart");
	}

	public M setIMEIEnd(java.lang.String IMEIEnd) {
		set("IMEIEnd", IMEIEnd);
		return (M)this;
	}
	
	public java.lang.String getIMEIEnd() {
		return getStr("IMEIEnd");
	}

	public M setSIMStart(java.lang.String SIMStart) {
		set("SIMStart", SIMStart);
		return (M)this;
	}
	
	public java.lang.String getSIMStart() {
		return getStr("SIMStart");
	}

	public M setSIMEnd(java.lang.String SIMEnd) {
		set("SIMEnd", SIMEnd);
		return (M)this;
	}
	
	public java.lang.String getSIMEnd() {
		return getStr("SIMEnd");
	}

	public M setBATStart(java.lang.String BATStart) {
		set("BATStart", BATStart);
		return (M)this;
	}
	
	public java.lang.String getBATStart() {
		return getStr("BATStart");
	}

	public M setBATEnd(java.lang.String BATEnd) {
		set("BATEnd", BATEnd);
		return (M)this;
	}
	
	public java.lang.String getBATEnd() {
		return getStr("BATEnd");
	}

	public M setVIPStart(java.lang.String VIPStart) {
		set("VIPStart", VIPStart);
		return (M)this;
	}
	
	public java.lang.String getVIPStart() {
		return getStr("VIPStart");
	}

	public M setVIPEnd(java.lang.String VIPEnd) {
		set("VIPEnd", VIPEnd);
		return (M)this;
	}
	
	public java.lang.String getVIPEnd() {
		return getStr("VIPEnd");
	}

	public M setIMEIRel(java.lang.Integer IMEIRel) {
		set("IMEIRel", IMEIRel);
		return (M)this;
	}
	
	public java.lang.Integer getIMEIRel() {
		return getInt("IMEIRel");
	}

	public M setTACInfo(java.lang.String TACInfo) {
		set("TACInfo", TACInfo);
		return (M)this;
	}
	
	public java.lang.String getTACInfo() {
		return getStr("TACInfo");
	}

	public M setCompanyName(java.lang.String CompanyName) {
		set("CompanyName", CompanyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("CompanyName");
	}

	public M setRemark1(java.lang.String Remark1) {
		set("Remark1", Remark1);
		return (M)this;
	}
	
	public java.lang.String getRemark1() {
		return getStr("Remark1");
	}

	public M setRemark2(java.lang.String Remark2) {
		set("Remark2", Remark2);
		return (M)this;
	}
	
	public java.lang.String getRemark2() {
		return getStr("Remark2");
	}

	public M setRemark3(java.lang.String Remark3) {
		set("Remark3", Remark3);
		return (M)this;
	}
	
	public java.lang.String getRemark3() {
		return getStr("Remark3");
	}

	public M setRemark4(java.lang.String Remark4) {
		set("Remark4", Remark4);
		return (M)this;
	}
	
	public java.lang.String getRemark4() {
		return getStr("Remark4");
	}

	public M setRemark5(java.lang.String Remark5) {
		set("Remark5", Remark5);
		return (M)this;
	}
	
	public java.lang.String getRemark5() {
		return getStr("Remark5");
	}

	public M setStatus(java.lang.Integer Status) {
		set("Status", Status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("Status");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

	public M setJstTemplate(java.lang.String jstTemplate) {
		set("JST_template", jstTemplate);
		return (M)this;
	}
	
	public java.lang.String getJstTemplate() {
		return getStr("JST_template");
	}

	public M setChtTemplate1(java.lang.String chtTemplate1) {
		set("CHT_template1", chtTemplate1);
		return (M)this;
	}
	
	public java.lang.String getChtTemplate1() {
		return getStr("CHT_template1");
	}

	public M setChtTemplate2(java.lang.String chtTemplate2) {
		set("CHT_template2", chtTemplate2);
		return (M)this;
	}
	
	public java.lang.String getChtTemplate2() {
		return getStr("CHT_template2");
	}

	public M setBatPrefix(java.lang.String batPrefix) {
		set("BAT_prefix", batPrefix);
		return (M)this;
	}
	
	public java.lang.String getBatPrefix() {
		return getStr("BAT_prefix");
	}

	public M setBatDigits(java.lang.String batDigits) {
		set("BAT_digits", batDigits);
		return (M)this;
	}
	
	public java.lang.String getBatDigits() {
		return getStr("BAT_digits");
	}

	public M setSimPrefix(java.lang.String simPrefix) {
		set("SIM_prefix", simPrefix);
		return (M)this;
	}
	
	public java.lang.String getSimPrefix() {
		return getStr("SIM_prefix");
	}

	public M setSimDigits(java.lang.String simDigits) {
		set("SIM_digits", simDigits);
		return (M)this;
	}
	
	public java.lang.String getSimDigits() {
		return getStr("SIM_digits");
	}

	public M setVipPrefix(java.lang.String vipPrefix) {
		set("VIP_prefix", vipPrefix);
		return (M)this;
	}
	
	public java.lang.String getVipPrefix() {
		return getStr("VIP_prefix");
	}

	public M setVipDigits(java.lang.String vipDigits) {
		set("VIP_digits", vipDigits);
		return (M)this;
	}
	
	public java.lang.String getVipDigits() {
		return getStr("VIP_digits");
	}

	public M setIccidPrefix(java.lang.String iccidPrefix) {
		set("ICCID_prefix", iccidPrefix);
		return (M)this;
	}
	
	public java.lang.String getIccidPrefix() {
		return getStr("ICCID_prefix");
	}

	public M setIccidDigits(java.lang.String iccidDigits) {
		set("ICCID_digits", iccidDigits);
		return (M)this;
	}
	
	public java.lang.String getIccidDigits() {
		return getStr("ICCID_digits");
	}

	public M setIMEIPrints(java.lang.String IMEIPrints) {
		set("IMEIPrints", IMEIPrints);
		return (M)this;
	}
	
	public java.lang.String getIMEIPrints() {
		return getStr("IMEIPrints");
	}

}
