package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsTestplan<M extends BaseGpsTestplan<M>> extends Model<M> implements IBean {

	public M setTestPlanId(java.lang.Integer TestPlanId) {
		set("TestPlanId", TestPlanId);
		return (M)this;
	}
	
	public java.lang.Integer getTestPlanId() {
		return getInt("TestPlanId");
	}

	public M setTestPlanName(java.lang.String TestPlanName) {
		set("TestPlanName", TestPlanName);
		return (M)this;
	}
	
	public java.lang.String getTestPlanName() {
		return getStr("TestPlanName");
	}

	public M setTestPlanDes(java.lang.String TestPlanDes) {
		set("TestPlanDes", TestPlanDes);
		return (M)this;
	}
	
	public java.lang.String getTestPlanDes() {
		return getStr("TestPlanDes");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

}
