package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsTcData<M extends BaseGpsTcData<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setSN(java.lang.String SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.String getSN() {
		return getStr("SN");
	}

	public M setFixMode(java.lang.String FixMode) {
		set("FixMode", FixMode);
		return (M)this;
	}
	
	public java.lang.String getFixMode() {
		return getStr("FixMode");
	}

	public M setGpsdb0(java.lang.Integer gpsdb0) {
		set("GpsDb_0", gpsdb0);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb0() {
		return getInt("GpsDb_0");
	}

	public M setGpsdb1(java.lang.Integer gpsdb1) {
		set("GpsDb_1", gpsdb1);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb1() {
		return getInt("GpsDb_1");
	}

	public M setGpsdb2(java.lang.Integer gpsdb2) {
		set("GpsDb_2", gpsdb2);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb2() {
		return getInt("GpsDb_2");
	}

	public M setGpsdb3(java.lang.Integer gpsdb3) {
		set("GpsDb_3", gpsdb3);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb3() {
		return getInt("GpsDb_3");
	}

	public M setGpsdb4(java.lang.Integer gpsdb4) {
		set("GpsDb_4", gpsdb4);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb4() {
		return getInt("GpsDb_4");
	}

	public M setGpsdb5(java.lang.Integer gpsdb5) {
		set("GpsDb_5", gpsdb5);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb5() {
		return getInt("GpsDb_5");
	}

	public M setGpsdb6(java.lang.Integer gpsdb6) {
		set("GpsDb_6", gpsdb6);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb6() {
		return getInt("GpsDb_6");
	}

	public M setGpsdb7(java.lang.Integer gpsdb7) {
		set("GpsDb_7", gpsdb7);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb7() {
		return getInt("GpsDb_7");
	}

	public M setGpsdb8(java.lang.Integer gpsdb8) {
		set("GpsDb_8", gpsdb8);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb8() {
		return getInt("GpsDb_8");
	}

	public M setGpsdb9(java.lang.Integer gpsdb9) {
		set("GpsDb_9", gpsdb9);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb9() {
		return getInt("GpsDb_9");
	}

	public M setGpsdb10(java.lang.Integer gpsdb10) {
		set("GpsDb_10", gpsdb10);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb10() {
		return getInt("GpsDb_10");
	}

	public M setGpsdb11(java.lang.Integer gpsdb11) {
		set("GpsDb_11", gpsdb11);
		return (M)this;
	}
	
	public java.lang.Integer getGpsdb11() {
		return getInt("GpsDb_11");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

}
