package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsUser<M extends BaseGpsUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("UserId");
	}

	public M setUserName(java.lang.String UserName) {
		set("UserName", UserName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("UserName");
	}

	public M setUserDes(java.lang.String UserDes) {
		set("UserDes", UserDes);
		return (M)this;
	}
	
	public java.lang.String getUserDes() {
		return getStr("UserDes");
	}

	public M setUserPwd(java.lang.String UserPwd) {
		set("UserPwd", UserPwd);
		return (M)this;
	}
	
	public java.lang.String getUserPwd() {
		return getStr("UserPwd");
	}

	public M setUserType(java.lang.String UserType) {
		set("UserType", UserType);
		return (M)this;
	}
	
	public java.lang.String getUserType() {
		return getStr("UserType");
	}

	public M setUserTestPlan(java.lang.String UserTestPlan) {
		set("UserTestPlan", UserTestPlan);
		return (M)this;
	}
	
	public java.lang.String getUserTestPlan() {
		return getStr("UserTestPlan");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

	public M setLoginTime(java.util.Date LoginTime) {
		set("LoginTime", LoginTime);
		return (M)this;
	}
	
	public java.util.Date getLoginTime() {
		return get("LoginTime");
	}

	public M setLoginStatus(java.lang.Integer LoginStatus) {
		set("LoginStatus", LoginStatus);
		return (M)this;
	}
	
	public java.lang.Integer getLoginStatus() {
		return getInt("LoginStatus");
	}

	public M setInService(java.lang.Boolean InService) {
		set("InService", InService);
		return (M)this;
	}
	
	public java.lang.Boolean getInService() {
		return get("InService");
	}

}
