package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsUsertype<M extends BaseGpsUsertype<M>> extends Model<M> implements IBean {

	public M setTypeId(java.lang.Integer TypeId) {
		set("TypeId", TypeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("TypeId");
	}

	public M setTypeName(java.lang.String TypeName) {
		set("TypeName", TypeName);
		return (M)this;
	}
	
	public java.lang.String getTypeName() {
		return getStr("TypeName");
	}

	public M setTypeDes(java.lang.String TypeDes) {
		set("TypeDes", TypeDes);
		return (M)this;
	}
	
	public java.lang.String getTypeDes() {
		return getStr("TypeDes");
	}

	public M setTestAutoTestSMT(java.lang.Boolean TestAutoTestSMT) {
		set("TestAutoTestSMT", TestAutoTestSMT);
		return (M)this;
	}
	
	public java.lang.Boolean getTestAutoTestSMT() {
		return get("TestAutoTestSMT");
	}

	public M setTestSMTOQC(java.lang.Boolean TestSMTOQC) {
		set("TestSMTOQC", TestSMTOQC);
		return (M)this;
	}
	
	public java.lang.Boolean getTestSMTOQC() {
		return get("TestSMTOQC");
	}

	public M setTestCouple(java.lang.Boolean TestCouple) {
		set("TestCouple", TestCouple);
		return (M)this;
	}
	
	public java.lang.Boolean getTestCouple() {
		return get("TestCouple");
	}

	public M setTestParamDownload(java.lang.Boolean TestParamDownload) {
		set("TestParamDownload", TestParamDownload);
		return (M)this;
	}
	
	public java.lang.Boolean getTestParamDownload() {
		return get("TestParamDownload");
	}

	public M setTestAutoTest(java.lang.Boolean TestAutoTest) {
		set("TestAutoTest", TestAutoTest);
		return (M)this;
	}
	
	public java.lang.Boolean getTestAutoTest() {
		return get("TestAutoTest");
	}

	public M setTestWriteImei(java.lang.Boolean TestWriteImei) {
		set("TestWriteImei", TestWriteImei);
		return (M)this;
	}
	
	public java.lang.Boolean getTestWriteImei() {
		return get("TestWriteImei");
	}

	public M setTestTwice(java.lang.Boolean TestTwice) {
		set("TestTwice", TestTwice);
		return (M)this;
	}
	
	public java.lang.Boolean getTestTwice() {
		return get("TestTwice");
	}

	public M setTestIncomCheck(java.lang.Boolean TestIncomCheck) {
		set("TestIncomCheck", TestIncomCheck);
		return (M)this;
	}
	
	public java.lang.Boolean getTestIncomCheck() {
		return get("TestIncomCheck");
	}

	public M setTestReadBackRom(java.lang.Boolean TestReadBackRom) {
		set("TestReadBackRom", TestReadBackRom);
		return (M)this;
	}
	
	public java.lang.Boolean getTestReadBackRom() {
		return get("TestReadBackRom");
	}

	public M setTestCartonBox(java.lang.Boolean TestCartonBox) {
		set("TestCartonBox", TestCartonBox);
		return (M)this;
	}
	
	public java.lang.Boolean getTestCartonBox() {
		return get("TestCartonBox");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

}
